### ISSUE TITLE
Not helpfull

### ISSUE THREAD

**Issue by j-tepe** [ghermans/bagisto-pickup#4]
The module is not helpfull at all. You still need to enter a shipper and trackingcode when the pickup method is chosen. You should make it in a way this is not needed anymore.

It should be like:

WHEN a customer has chosen the pick up at store method
THEN admin can press the ship button in the backend an set the status to picked up

**Comment by ghermans** [comment]
Thank you for the feedback as i appreciate it, at the moment the extension is still in a development phase, it has already been made public available to collect ideas and questions.

The problems you are currently experiencing will be solved ASAP.

**Comment by ghermans** [comment]
@jtepe-sedna I have discussed this internally with my colleagues within the Bagisto team, we are going to make a change in Bagisto that when you click on the ship button the carrier is automatically filled in and the track & trace field becomes optional.
You can follow the progress of this [here](https://github.com/bagisto/bagisto/issues/3451)

**Comment by ghermans** [comment]
@jtepe-sedna the issue should be fixed now in Bagisto, please pull the latest changes from the Bagisto github repository.
