### ISSUE TITLE
View cache return error

### ISSUE THREAD

**Issue by jaseelbavu** [ghermans/bagisto-pickup#5]
`php artisan view:cache` returns an error.

![Screenshot from 2020-08-20 19-34-39](https://user-images.githubusercontent.com/22430734/90781517-46860880-e31c-11ea-9fbb-bb02d3d8f44a.png)

```php
$this->loadViewsFrom(__DIR__.'/../resources/views', 'pickup');
```

This line in PickupServiceProvider.php is returning the errors.

**Comment by ghermans** [comment]
@jaseelbavu  thanks for providing the feedback, i will publish a fix for this during the weekend.
