### ISSUE TITLE
Compatible with v1.3 ?

### ISSUE THREAD

**Issue by blackyzero** [ghermans/bagisto-pickup#7]
Hello,

I got this error during installation,
`Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Using version dev-master for digibytes/pickup
./composer.json has been updated
Running composer update digibytes/pickup --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires khaled.alshamaa/ar-php ^6.0.0, found khaled.alshamaa/ar-php[v6.0.0] but the package is fixed to v5.5.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

Please advise how to fix it.
Thank you.

**Comment by ghermans** [comment]
Hi @blackyzero this package is compatible with 1.3.0 as i just did a fresh install of Bagisto (v1.3.0) and this package and couldn't reproduce your issue

```sh
Using version dev-master for digibytes/pickup
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing digibytes/pickup (dev-master 1cf7937): Cloning 1cf7937bfe from cache
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: astrotomic/laravel-translatable
Discovered Package: babenkoivan/elastic-client
Discovered Package: babenkoivan/elastic-scout-driver
Discovered Package: bagisto/bagisto-package-generator
Discovered Package: bagistobrasil/bagisto-product-social-share
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: digibytes/pickup
Discovered Package: fideloper/proxy
Discovered Package: flynsarmy/db-blade-compiler
Discovered Package: intervention/image
Discovered Package: kalnoy/nestedset
Discovered Package: konekt/concord
Discovered Package: konekt/enum-eloquent
Discovered Package: laravel/scout
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prettus/l5-repository
Discovered Package: tymon/jwt-auth
Package manifest generated successfully.


```

**Comment by blackyzero** [comment]
strange, i also did fresh install Bagisto, but still getting same issue when trying to install this extension.
Do you have any idea how to make it works?

Thank you.

**Comment by ghermans** [comment]
@blackyzero the issue seems to be caused by Bagisto, a issue report for this exists on https://github.com/bagisto/bagisto/issues/4654 and a fix will be provided in 1.3.1

In the meanwhile what you could do as a workaround is

1. Remove the vendor directory (in case this folder exists).
2. Remove the file **composer.lock** from your Bagisto root folder.
3. run **composer install**

**Comment by blackyzero** [comment]
Thanks @ghermans for this suggestion
I am still not able to install this extension. After following yours, and execute the install command, it shows as below, but there is no store pickup in Carrier setting.

`composer require digibytes/pickup
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Using version dev-master for digibytes/pickup
./composer.json has been updated
Running composer update digibytes/pickup
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: astrotomic/laravel-translatable
Discovered Package: babenkoivan/elastic-client
Discovered Package: babenkoivan/elastic-scout-driver
Discovered Package: bagisto/bagisto-package-generator
Discovered Package: bagistobrasil/bagisto-product-social-share
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: digibytes/pickup
Discovered Package: fideloper/proxy
Discovered Package: flynsarmy/db-blade-compiler
Discovered Package: intervention/image
Discovered Package: kalnoy/nestedset
Discovered Package: konekt/concord
Discovered Package: konekt/enum-eloquent
Discovered Package: laravel/scout
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prettus/l5-repository
Discovered Package: tymon/jwt-auth
Package manifest generated successfully.
80 packages you are using are looking for funding.
Use the `composer fund` command to find out more!`

**Comment by ghermans** [comment]
Please run  `php artisan optimize` and see if the option comes available in admin shipping methods

**Comment by blackyzero** [comment]
great command. it works.
Thanks @ghermans !
